displayName=Dim Light
author=JD-Michelena
description=Dim the game screen from 0 to 100% in any area.
tags=brightness,dark,dim,117hd,light
plugins=com.dimlight.DimLightPlugin
version=1.0.0
build=standard
